kind: pipeline
name: default
environment:
  USERNAME:
    from_secret: subtoken
  DRONE_REMOTE_URL: https://$USERNAME@tomasky/denok.git
  
steps:
- name: test
  image: hayd/alpine-deno:1.4.6


  commands:
  - apk add git 
  - git clone https://$USERNAME@tomasky/denok.git
  - deno --version
  - cd example && deno cache main.ts
  
- name: publish
  image: plugins/docker:18
   
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: ./example/Dockerfile
    context: ./example
    repo: registry.gitlab.com/weezway/deno-https-server
    registry: registry.gitlab.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag
