kind: pipeline
name: default
type: docker

   
steps:
- name: test
  image: hayd/alpine-deno:1.4.6

  environment:
    gituser:
      from_secret: git_user
  commands:
  - echo $${gituser}
  - apk add git 
  - git clone https://$${gituser}@tomasky/denok.git
  - deno --version
  - cd example && deno cache main.ts
  
- name: publish
  image: plugins/docker:18
   
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: ./example/Dockerfile
    context: ./example
    repo: registry.gitlab.com/weezway/deno-https-server
    registry: registry.gitlab.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag
